export const LOAD_CLIENTS_STARTED = 'LOAD_CLIENTS_STARTED';
export const LOAD_CLIENTS_COMPLETED = 'LOAD_CLIENTS_COMPLETED';

export const CREATE_CLIENT = 'CREATE_CLIENT';
export const ADD_CLIENT = 'ADD_CLIENT';
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const SAVE_CLIENT = 'SAVE_CLIENT';
export const REMOVE_CLIENT = 'REMOVE_CLIENT';